// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (id, user_id, action, entity_type, entity_id, details, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, action, entity_type, entity_id, details, created_at
`

type CreateAuditLogParams struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	Action     string
	EntityType string
	EntityID   sql.NullString
	Details    sql.NullString
	CreatedAt  time.Time
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, createAuditLog,
		arg.ID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogs = `-- name: GetAuditLogs :many
SELECT a.id, a.user_id, a.action, a.entity_type, a.entity_id, a.details, a.created_at, u.name as user_name FROM audit_logs a
LEFT JOIN users u ON a.user_id = u.id
ORDER BY a.created_at DESC
`

type GetAuditLogsRow struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	Action     string
	EntityType string
	EntityID   sql.NullString
	Details    sql.NullString
	CreatedAt  time.Time
	UserName   sql.NullString
}

func (q *Queries) GetAuditLogs(ctx context.Context) ([]GetAuditLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAuditLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuditLogsRow
	for rows.Next() {
		var i GetAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
