// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contents.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createContent = `-- name: CreateContent :one
INSERT INTO contents (id, title, category, content, feedback, author_id, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, 'Draft', NOW(), NOW())
RETURNING id, title, category, content, feedback, author_id, status, created_at, updated_at
`

type CreateContentParams struct {
	ID       uuid.UUID
	Title    string
	Category string
	Content  string
	Feedback sql.NullString
	AuthorID uuid.UUID
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (Content, error) {
	row := q.db.QueryRowContext(ctx, createContent,
		arg.ID,
		arg.Title,
		arg.Category,
		arg.Content,
		arg.Feedback,
		arg.AuthorID,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Feedback,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContent = `-- name: DeleteContent :exec
DELETE FROM contents WHERE id = $1
`

func (q *Queries) DeleteContent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteContent, id)
	return err
}

const getContentByID = `-- name: GetContentByID :one
SELECT c.id, c.title, c.category, c.content, c.feedback, c.author_id, c.status, c.created_at, c.updated_at,
       u.name as author_name,
       p.plan_date
FROM contents c
JOIN users u ON c.author_id = u.id
LEFT JOIN plans p ON p.content_id = c.id
WHERE c.id = $1
`

type GetContentByIDRow struct {
	ID         uuid.UUID
	Title      string
	Category   string
	Content    string
	Feedback   sql.NullString
	AuthorID   uuid.UUID
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	AuthorName string
	PlanDate   sql.NullTime
}

func (q *Queries) GetContentByID(ctx context.Context, id uuid.UUID) (GetContentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getContentByID, id)
	var i GetContentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Feedback,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.PlanDate,
	)
	return i, err
}

const getContents = `-- name: GetContents :many
SELECT c.id, c.title, c.category, c.content, c.feedback, c.author_id, c.status, c.created_at, c.updated_at,
       u.name as author_name,
       p.plan_date
FROM contents c
JOIN users u ON c.author_id = u.id
LEFT JOIN plans p ON p.content_id = c.id
ORDER BY c.created_at DESC
`

type GetContentsRow struct {
	ID         uuid.UUID
	Title      string
	Category   string
	Content    string
	Feedback   sql.NullString
	AuthorID   uuid.UUID
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	AuthorName string
	PlanDate   sql.NullTime
}

func (q *Queries) GetContents(ctx context.Context) ([]GetContentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getContents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContentsRow
	for rows.Next() {
		var i GetContentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Content,
			&i.Feedback,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.PlanDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewContent = `-- name: ReviewContent :one
UPDATE contents
SET status = $2, feedback = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, title, category, content, feedback, author_id, status, created_at, updated_at
`

type ReviewContentParams struct {
	ID       uuid.UUID
	Status   string
	Feedback sql.NullString
}

// Manajer: approve atau minta revisi (feedback wajib jika Revision)
func (q *Queries) ReviewContent(ctx context.Context, arg ReviewContentParams) (Content, error) {
	row := q.db.QueryRowContext(ctx, reviewContent, arg.ID, arg.Status, arg.Feedback)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Feedback,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContent = `-- name: UpdateContent :one
UPDATE contents
SET title = $2, category = $3, content = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, title, category, content, feedback, author_id, status, created_at, updated_at
`

type UpdateContentParams struct {
	ID       uuid.UUID
	Title    string
	Category string
	Content  string
}

func (q *Queries) UpdateContent(ctx context.Context, arg UpdateContentParams) (Content, error) {
	row := q.db.QueryRowContext(ctx, updateContent,
		arg.ID,
		arg.Title,
		arg.Category,
		arg.Content,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Feedback,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContentStatus = `-- name: UpdateContentStatus :one
UPDATE contents
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, title, category, content, feedback, author_id, status, created_at, updated_at
`

type UpdateContentStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateContentStatus(ctx context.Context, arg UpdateContentStatusParams) (Content, error) {
	row := q.db.QueryRowContext(ctx, updateContentStatus, arg.ID, arg.Status)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Feedback,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
