// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Content struct {
	ID        uuid.UUID
	Title     string
	Category  string
	Content   string
	Feedback  sql.NullString
	AuthorID  uuid.UUID
	Status    string // Draft | Review | Revision | Approved
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Plan struct {
	ID        uuid.UUID
	Pic       string
	Pillar    string
	ContentID uuid.NullUUID
	PlanDate  time.Time
	Status    string // Planned | In Progress | Completed
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Role      string // Manajer | Kreator
	Status    string // Active | Offline
	CreatedAt time.Time
	UpdatedAt time.Time
}
