// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID         uuid.UUID
	UserID     uuid.NullUUID
	Action     string
	EntityType string
	EntityID   sql.NullString
	Details    sql.NullString
	CreatedAt  time.Time
}

type Content struct {
	ID        uuid.UUID
	Title     string
	Category  string
	Content   string
	Feedback  sql.NullString
	AuthorID  uuid.UUID
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Plan struct {
	ID        uuid.UUID
	Pic       string
	Pillar    string
	ContentID uuid.NullUUID
	PlanDate  time.Time
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Role      string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
