// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// ─── UpsertPlan ──────────────────────────────────────────────────────────────

const upsertPlan = `-- name: UpsertPlan :one
INSERT INTO plans (id, pic, pillar, content_id, plan_date, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
ON CONFLICT (plan_date) DO UPDATE
    SET pic        = EXCLUDED.pic,
        pillar     = EXCLUDED.pillar,
        content_id = EXCLUDED.content_id,
        status     = EXCLUDED.status,
        updated_at = NOW()
RETURNING id, pic, pillar, content_id, plan_date, status, created_at, updated_at
`

type UpsertPlanParams struct {
	ID        uuid.UUID
	Pic       string
	Pillar    string
	ContentID uuid.NullUUID
	PlanDate  time.Time
	Status    string
}

func (q *Queries) UpsertPlan(ctx context.Context, arg UpsertPlanParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, upsertPlan,
		arg.ID,
		arg.Pic,
		arg.Pillar,
		arg.ContentID,
		arg.PlanDate,
		arg.Status,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Pic,
		&i.Pillar,
		&i.ContentID,
		&i.PlanDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ─── GetPlanByDate ───────────────────────────────────────────────────────────

const getPlanByDate = `-- name: GetPlanByDate :one
SELECT id, pic, pillar, content_id, plan_date, status, created_at, updated_at FROM plans
WHERE plan_date = $1
`

func (q *Queries) GetPlanByDate(ctx context.Context, planDate time.Time) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlanByDate, planDate)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Pic,
		&i.Pillar,
		&i.ContentID,
		&i.PlanDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ─── GetPlansByDateRange ─────────────────────────────────────────────────────

const getPlansByDateRange = `-- name: GetPlansByDateRange :many
SELECT id, pic, pillar, content_id, plan_date, status, created_at, updated_at FROM plans
WHERE plan_date >= $1 AND plan_date <= $2
ORDER BY plan_date ASC
`

type GetPlansByDateRangeParams struct {
	StartDate time.Time
	EndDate   time.Time
}

func (q *Queries) GetPlansByDateRange(ctx context.Context, arg GetPlansByDateRangeParams) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, getPlansByDateRange, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Pic,
			&i.Pillar,
			&i.ContentID,
			&i.PlanDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ─── GetAllPlans ─────────────────────────────────────────────────────────────

const getAllPlans = `-- name: GetAllPlans :many
SELECT id, pic, pillar, content_id, plan_date, status, created_at, updated_at FROM plans
ORDER BY plan_date ASC
`

func (q *Queries) GetAllPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Pic,
			&i.Pillar,
			&i.ContentID,
			&i.PlanDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ─── GetAvailablePlans ───────────────────────────────────────────────────────

const getAvailablePlans = `-- name: GetAvailablePlans :many
SELECT id, pic, pillar, content_id, plan_date, status, created_at, updated_at FROM plans
WHERE content_id IS NULL AND status = 'Planned'
ORDER BY plan_date ASC
`

func (q *Queries) GetAvailablePlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, getAvailablePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Pic,
			&i.Pillar,
			&i.ContentID,
			&i.PlanDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ─── AssignContentAndSetReview ───────────────────────────────────────────────

const assignContentAndSetReview = `-- name: AssignContentAndSetReview :one
UPDATE plans
SET content_id = $2, status = 'Review', updated_at = NOW()
WHERE plan_date = $1
RETURNING id, pic, pillar, content_id, plan_date, status, created_at, updated_at
`

type AssignContentAndSetReviewParams struct {
	PlanDate  time.Time
	ContentID uuid.NullUUID
}

func (q *Queries) AssignContentAndSetReview(ctx context.Context, arg AssignContentAndSetReviewParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, assignContentAndSetReview, arg.PlanDate, arg.ContentID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Pic,
		&i.Pillar,
		&i.ContentID,
		&i.PlanDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ─── UpdatePlanStatusByContentID ─────────────────────────────────────────────

const updatePlanStatusByContentID = `-- name: UpdatePlanStatusByContentID :one
UPDATE plans
SET status = $2, updated_at = NOW()
WHERE content_id = $1
RETURNING id, pic, pillar, content_id, plan_date, status, created_at, updated_at
`

type UpdatePlanStatusByContentIDParams struct {
	ContentID uuid.NullUUID
	Status    string
}

func (q *Queries) UpdatePlanStatusByContentID(ctx context.Context, arg UpdatePlanStatusByContentIDParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, updatePlanStatusByContentID, arg.ContentID, arg.Status)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Pic,
		&i.Pillar,
		&i.ContentID,
		&i.PlanDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ─── UpdatePlanStatus ────────────────────────────────────────────────────────

const updatePlanStatus = `-- name: UpdatePlanStatus :one
UPDATE plans
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, pic, pillar, content_id, plan_date, status, created_at, updated_at
`

type UpdatePlanStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdatePlanStatus(ctx context.Context, arg UpdatePlanStatusParams) (Plan, error) {
	row := q.db.QueryRowContext(ctx, updatePlanStatus, arg.ID, arg.Status)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Pic,
		&i.Pillar,
		&i.ContentID,
		&i.PlanDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

// ─── DeletePlan ──────────────────────────────────────────────────────────────

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE plan_date = $1
`

func (q *Queries) DeletePlan(ctx context.Context, planDate time.Time) error {
	_, err := q.db.ExecContext(ctx, deletePlan, planDate)
	return err
}
